### ISSUE TITLE
Express API

### ISSUE THREAD

**Issue by msitruk** [austincunningham/keycloak-express-openid-client#1]
If i use express as rest API for my angular app with keycloak JS should i use part of your repo to validate user auth on some endpoints. Should i add another API specific sécurity layer with jwt ?

**Comment by msitruk** [comment]
Some extra infos if you want to secure express api u still need to add jwt : https://curity.io/resources/learn/oidc-node-express/#secure-endpoints-with-jwts

**Comment by austincunningham** [comment]
It's been about 4 years since I have used angular, so took me a while to test. 
You can secure the rest endpoints directly and the redirect to keycloak works as expected. As some angular routes may have multiple rest request I would consider securing angular directly with keycloak see [this blog which I haven't tried](https://medium.com/keycloak/secure-angular-app-with-keycloak-63ec934e5093) . That said you should probably have both your frontend and backend secured with an auth (e.g. keycloak)
